TrainerNames: ; 399ff (e:59ff)
	db "YOUNGSTER@"
	db "BUG CATCHER@"
	db "LASS@"
	db "SAILOR@"
	db "JR.TRAINER♂@"
	db "JR.TRAINER♀@"
	db "POKéMANIAC@"
	db "SUPER NERD@"
	db "HIKER@"
	db "BIKER@"
	db "BURGLAR@"
	db "ENGINEER@"
	db "JUGGLER@"
	db "FISHERMAN@"
	db "SWIMMER@"
	db "CUE BALL@"
	db "GAMBLER@"
	db "BEAUTY@"
	db "PSYCHIC@"
	db "ROCKER@"
	db "JUGGLER@"
	db "TAMER@"
	db "BIRD KEEPER@"
	db "BLACKBELT@"
	db "RIVAL1@"
	db "PROF.OAK@"
	db "CHIEF@"
	db "SCIENTIST@"
	db "DEADMAU5@"
	db "TEAM 5 GRUNT@"
	db "COOLTRAINER♂@"
	db "COOLTRAINER♀@"
	db "ZEDD@"
	db "GUETTA@"
	db "KREWELLA@"
	db "AFROJACK@"
	db "AVICII@"
	db "PORTER@"
	db "DIPLO@"
	db "AOKI@"
	db "GENTLEMAN@"
	db "RIVAL2@"
	db "RIVAL3@"
	db "BUUREN@"
	db "GUARDIAN@"
	db "TIESTO@"
	db "DAFTPUNK@"
	db "KARMA@"
	db "EMMA@"
	db "CHRIS@"
	db "LEE@"
	db "FINN@"
	db "GEORGE@"
	db "MIKE@"
	db "BEN@"